[versions]
ben-manes-versions = "0.48.0"
kotest = "5.7.2"
kotlin = "1.9.20-Beta"
kotlinter = "3.16.0"
mockk = "1.13.7"
spring-data-mongodb = "3.1.3"
version-catalog-update = "0.8.1"

[libraries]
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
spring-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb", version.ref = "spring-data-mongodb" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
kotiln-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
